name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: 'Breaking'
    labels:
      - 'breaking'
      - 'major'
  - title: 'New'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: 'Maintenance'
    labels:
      - 'maintenance'
  - title: 'Documentation'
    labels:
      - 'docs'
  - title: 'Other changes'
  - title: 'Dependency updates'
    labels:
      - 'dependencies'
    collapse-after: 5

version-resolver:
  major:
    labels:
      - 'breaking'
      - 'major'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'type: bug'
      - 'type: fix'
      - 'type: maintenance'
      - 'type: docs'
      - 'type: dependencies'
      - 'type: security'

exclude-labels:
  - 'skip-changelog'
